spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-route
              uri: http://auth-service:4001
              predicates:
                - Path=/auth/**, /oauth2/**, /login/oauth2/**
              filters:
                - StripPrefix=0

            - id: genders-open-route
              uri: http://user-profile-service:4002
              predicates:
                - Path=/api/v1/genders
              filters:
                - StripPrefix=0

            - id: user-profile-service-route
              uri: http://user-profile-service:4002
              predicates:
                - Path=/api/v1/**
              filters:
                - StripPrefix=0
                - JwtValidation

server:
  port: 4000

auth:
  service:
    url: ${AUTH_SERVICE_URL}