spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-route
              uri: http://auth-service:4001
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=0


server:
  port: 4000


auth:
  service:
    url: ${AUTH_SERVICE_URL}