spring:
  application:
    name: media-service

  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:media-db}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:media_service_db}
      username: ${SPRING_DATA_MONGODB_USERNAME:root}
      password: ${SPRING_DATA_MONGODB_PASSWORD:secret}
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}

server:
  port: 4003